[package]
name = "example"
version = "0.1.0"
authors = ["lz"]
edition = "2018"

[dependencies]
rustls = "0.15"
actix-web = { version = "1.0.0", features=["rust-tls"] }
bytes = "0.4"
futures = "0.1"
env_logger = "0.6.2"
log = "0.4"

