[package]
name = "signer"
version = "0.1.0"
authors = ["alexeyz"]

[dependencies]
ring = { version = "0.13.2", features = [ "rsa_signing" ] }
untrusted = "*"
clap = {version = "~2.27.0", features = ["yaml"] }


