[package]
name = "maze"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-modbus = { version = "0.16", default-features = false, features = ["tcp-sync"] }

[[bin]]
name = "maze"
path = "main.rs"
