[package]
name = "server"
version = "0.1.0"
authors = ["lz"]
edition = "2018"

[dependencies]
hyper = "0.13.0"
tokio = { version = "0.2", features = ["full"] }
failure = "0.1.6"
reqwest = "0.9.24"
futures = "0.3.4"
